package AddModule;


/**
* AddModule/AddModulePOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addmodule.idl
* Sunday, 28 May, 2023 10:13:36 PM IST
*/

public abstract class AddModulePOA extends org.omg.PortableServer.Servant
 implements AddModule.AddModuleOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("add", new java.lang.Integer (0));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // AddModule/AddModule/add
       {
         double d1 = in.read_double ();
         double d2 = in.read_double ();
         double $result = (double)0;
         $result = this.add (d1, d2);
         out = $rh.createReply();
         out.write_double ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:AddModule/AddModule:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public AddModule _this() 
  {
    return AddModuleHelper.narrow(
    super._this_object());
  }

  public AddModule _this(org.omg.CORBA.ORB orb) 
  {
    return AddModuleHelper.narrow(
    super._this_object(orb));
  }


} // class AddModulePOA
