package AddModule;


/**
* AddModule/AddModuleOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addmodule.idl
* Sunday, 28 May, 2023 10:13:36 PM IST
*/

public interface AddModuleOperations 
{
  double add (double d1, double d2);
} // interface AddModuleOperations
