package AddModule;


/**
* AddModule/AddModule.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addmodule.idl
* Sunday, 28 May, 2023 10:13:36 PM IST
*/

public interface AddModule extends AddModuleOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface AddModule
