package AddModule;


/**
* AddModule/AddModuleHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addmodule.idl
* Sunday, 28 May, 2023 10:13:36 PM IST
*/

abstract public class AddModuleHelper
{
  private static String  _id = "IDL:AddModule/AddModule:1.0";

  public static void insert (org.omg.CORBA.Any a, AddModule.AddModule that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static AddModule.AddModule extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (AddModule.AddModuleHelper.id (), "AddModule");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static AddModule.AddModule read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_AddModuleStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, AddModule.AddModule value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static AddModule.AddModule narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddModule.AddModule)
      return (AddModule.AddModule)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddModule._AddModuleStub stub = new AddModule._AddModuleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static AddModule.AddModule unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof AddModule.AddModule)
      return (AddModule.AddModule)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      AddModule._AddModuleStub stub = new AddModule._AddModuleStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
