package AddModule;

/**
* AddModule/AddModuleHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Addmodule.idl
* Sunday, 28 May, 2023 10:13:36 PM IST
*/

public final class AddModuleHolder implements org.omg.CORBA.portable.Streamable
{
  public AddModule.AddModule value = null;

  public AddModuleHolder ()
  {
  }

  public AddModuleHolder (AddModule.AddModule initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = AddModule.AddModuleHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    AddModule.AddModuleHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return AddModule.AddModuleHelper.type ();
  }

}
